name: Deploy CI

on: 
  push:
    brances: 
      ['main']

jobs:
  build-check-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Check index.html
        run: |
          if [ ! -f ./public/index.html ]; then
            echo "Arquivo inexistente, cancelando deploy!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public