name: Deploy CI

on: 
  push:
    branches: 
      - main

jobs:
  build-check-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check index
        run: |
          if [ ! -f ./public/index.html ]; then
            echo "Arquivo inexistente, cancelando deploy!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ././public
